micronaut:
  application:
    name: prenoto
  router:
    static-resources:
      default:
        enabled: true
        mapping: /**
        paths: classpath:public
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: changeMechangeMechangeMechangeMechangeMechangeMe
    endpoints:
      login:
        path: /api/login
      logout:
        path: /api/logout
    interceptUrlMap:
      - pattern: /**.html
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: /
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: /**.js
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: /**.css
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: /assets/i18n/**.json
        httpMethod: GET
        access:
          - isAnonymous()
  server:
    cors:
      enabled: true
      configurations:
        web:
          allowedMethods:
            - POST
            - PUT
            - DELETE
            - GET
datasources:
  default:
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
jpa.default.properties.hibernate.hbm2ddl.auto: update

